---
sudo: false
dist: trusty
language: node_js
node_js:
  - '12'

before_install:
  - touch package.json

install:
  - make

script:
  - npx @commitlint/travis-cli
  - make lint

env:
  global:
    - MAKEFLAGS="-j2"

    # NPM_TOKEN (robertrossmann)
    - secure: "PkRKNN3qJTTrWCS/kPnexLrNYoM+qg/RWSyNFBLitIcZVZ+qN8oBhVo9m8ZHwVBW+ASTUNQOAYb3Y1kh23A5Or0xsxTTDiFJxWn6eGc7madQ1kXqe33+/ZNFnv7Bg3iK7kg6gogOCmBTgcg0RrF5p8uk01tEZuRfeUIfSfMW9+2VyFvU3MYySsqgNL9DTI149pls/Il0e5EXXXkgOH6AIRuj6MaTFXXRtVb63lZysGQ1bAEp0MAt6JF0WesK4iR57OaB9F0NPV48879yBNsNtxkN+RbMCsFUoAB4mRWCCCPdpXwl9UaJ4Te+TZ2kHNOPdSV27QxlBlbxQ2Lm+eF0rcfGmn/yEGP07y0IU7c20NAyz6Xa399ASVi0BXCK/wpSUsKHDQ3POvq2pm0g5/uxRr9VvhZBWeHFKTSCmesBGlMqZ81ShfXGPKxtVM1HafgbF/Z/yDtf73VVJ8J+xCPK9VLkwI5kNHS0s/ojbBKN2W1pz1Trr3BOGt0RUBhzrFFP1AQE4J0tijGu13eJ8u08kzw6u9GDUSyRHbDgx+rWDyKHMrdhmoWYkDvPrq9/KIUbTOx+PGf1kfj9GqvlHFLz2I/fUGnKZs8gch6AG8wTNM5KnWRyS6KgeCUSRnGMTvpOipu3K7sYIzcIXdfOf6rsJ4c7NWm49L6RnmvuXf3ySvA="

before_deploy: ci/before-deploy.sh

deploy:
  skip_cleanup: true
  provider: script
  script: utils/release.sh
  on:
    repo: strvcom/code-quality-tools
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^release\/.{1,}$
    node: '12'
