---
name: Deploy
on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    env:
      CI: 'true'

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Fetch tags
        run: git fetch --tags origin release

      - run: make install

      - name: Authenticate npm
        run: ./utils/ci/npm-auth.sh
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Release
        run: npx lerna publish from-git --yes
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Merge release
        run: ./utils/ci/sync-release.sh
        if: success()
