---
name: Code Quality Checks
on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-18.04
    env:
      CI: 'true'

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 50
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: make install
      - run: make lint
